global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Drawing;
global using Microsoft.AspNetCore.Identity;
global using Ticky.Base.Converters;
global using Ticky.Base.DTOs;
global using Ticky.Base.Entities.Abstractions;
global using Ticky.Base.Enums;
global using Ticky.Base.Validation;
